export const IMAGES = {
  welcomeHero: "/images/welcome-sushi-hero.webp",
  welcomeLogo: "/images/welcome-logo-animated.webp",
  logo: "/images/logo-rolou-sushi.webp",
  logoIcon: "/images/logo-rolou-sushi-icon.webp",
  counter: "/images/sushi-counter-character.webp",
  spinner: "/images/loading-sushi-spinner.webp",
  error: "/images/error-sushi-oops.webp",
  empty: "/images/empty-state-sushi.webp",
  confetti: "/images/confetti-sushi.webp",
  celebration: "/images/group-created-celebration.webp",
  invitationBg: "/images/invitation-card-bg.webp",
  qrFrame: "/images/qr-code-frame.webp",
  patternSubtle: "/images/pattern-sushi-subtle.webp",
  patternJapanese: "/images/pattern-japanese-elements.webp",
  iconPlus: "/images/icon-plus-sushi.webp",
  iconMinus: "/images/icon-minus-sushi.webp",
  iconShare: "/images/icon-share-sushi.webp",
  badgeFirst: "/images/badge-first-roll.webp",
  badgeMaster: "/images/badge-sushi-master.webp",
  badgeLegend: "/images/badge-sushi-legend.webp",
} as const;

export const MILESTONES = [10, 25, 50, 100] as const;

export const STRINGS = {
  appName: "Rolou Sushi",
  welcome: {
    title: "Rolou Sushi!",
    subtitle: "Conte quantos sushis você e seus amigos comeram!",
    createGroup: "Criar Grupo",
    joinGroup: "Entrar em Grupo",
    continueSession: "Continuar",
  },
  username: {
    title: "Qual seu nome?",
    placeholder: "Seu nome ou apelido",
    continue: "Continuar",
    validation: "Digite um nome com pelo menos 2 caracteres",
  },
  createGroup: {
    title: "Criar Grupo",
    namePlaceholder: "Nome do grupo (ex: Janta de Sexta)",
    create: "Criar",
    success: "Grupo criado!",
    shareMessage: "Compartilhe o código com seus amigos:",
    goToGroup: "Ir para o Grupo",
    copyCode: "Copiar Código",
    copied: "Copiado!",
    shareInvite: "Compartilhar Convite",
  },
  joinGroup: {
    title: "Entrar em Grupo",
    codePlaceholder: "Código do grupo (6 caracteres)",
    join: "Entrar",
    notFound: "Grupo não encontrado. Verifique o código.",
    alreadyMember: "Você já está neste grupo!",
  },
  counter: {
    title: "Seus Sushis",
    add: "Adicionar",
    quickAdd: "Adicionar Rápido",
  },
  leaderboard: {
    title: "Ranking",
    you: "(você)",
    empty: "Ninguém comeu sushi ainda!",
    sushi: "sushis",
    sushiSingular: "sushi",
  },
  invite: {
    title: "Convidar Amigos",
    code: "Código do Grupo",
    scanQr: "Escaneie o QR Code",
    orShareLink: "Ou compartilhe o link:",
    copyLink: "Copiar Link",
    share: "Compartilhar",
  },
  milestones: {
    10: "Primeiro prato!",
    25: "Sushi lover!",
    50: "Mestre do Sushi!",
    100: "Lenda do Sushi!",
  } as Record<number, string>,
  errors: {
    generic: "Ops! Algo deu errado.",
    tryAgain: "Tentar Novamente",
    groupNotFound: "Grupo não encontrado",
    connectionError: "Erro de conexão. Verifique sua internet.",
  },
  loading: "Carregando...",
} as const;
